name: release

on:
  workflow_dispatch:
    inputs:
      kind:
        description: 'Release kind'
        required: false
        default: 'auto'
        type: choice
        options: [auto, major, minor, patch]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: bun install

      - name: Release
        run: bunx fuman-build release --kind ${{ inputs.kind }} --with-npm --with-github-release --github-token ${{ secrets.GITHUB_TOKEN }}